fieldLayouts:
  a62dfaae-e57f-490d-947c-c02c5ae24974:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 75
          -
            fieldUid: 6444601d-97cd-4c6d-a6f7-0ba81d83544f # CategorieÃ«n
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 6a97301e-c65c-412b-80f0-1021ac5db6c3 # Samenvatting
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: 63284e79-c995-4800-a887-532736269464 # Uitgelichte afbeelding
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 2113a2f7-8815-4024-bfa5-c62bf9d16979 # Startdatum
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 7d5c0470-3ff6-41c9-8226-9d80fc761bcc # Einddatum
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 1980f1ed-d081-49d2-b2be-c55ce0de6c51 # Detail Hero
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: e42088b5-9a48-4aaf-892e-092dbd342e50 # Gedetailleerde lijst
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6bdb6206-bf46-424b-8084-4776e7cfcb6a # Formulier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b67271c9-deaf-4f52-91f6-3392469feae8 # Blokken
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 163f8077-5e22-4216-a8dc-96c62b8cc736 # Kaart Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 520cbb57-c5ea-454f-b55d-6dd4e583f47f # Kaart omschrijving
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Kaart info'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 07654c5b-71aa-4d1b-9599-b38ec64e4d69 # SEOMatic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: agendaItem
hasTitleField: true
name: Agenda
section: 76a53ca8-58e7-43da-b682-0d16c2be5edd # Agenda
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
